version: '3.7'
services:
  react:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/learn-frontend
      - ./learn-frontend/node_modules:/learn-frontend/node_modules
    ports:
      - 5173:5173
    command: sh -c "cd learn-frontend && npm run dev"
volumes:
  node_modules: