version: '3.7'
services:
  react:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
      - node_modules:/app/node_modules
    ports:
      - 5173:5173
    command: sh -c "cd /app && yarn dev"
volumes:
  node_modules: